default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: railstest_development

test:
  <<: *default
  database: railstest_test

production:
  <<: *default
  username: admin
  password: ftsje6s7
  socket: /var/lib/mysql/mysql.sock
  host: rds-temperature02.cdzn2wjjzkbn.us-east-1.rds.amazonaws.com
  database: railstest_production
